language: node_js
node_js:
- node
cache: npm
script: npm run deploy
after_script: npm run alias
addons:
  ssh_known_hosts: 
  - github.com
  - 192.30.253.112
  - 192.30.253.113
env:
  global:
    secure: Z5unXwLrJ2OKbo7ohHrYewt5JWc3rMltSFRGgrnjHCv4XR0GbqbP6uNg1BwffXCwUvDGJnGovLlYR0Bd9mviursEdWInx/Hs0GQIqpAWlYhy4d4SWvDTkwGXNvL4wDFvJn/oo1saWpu4YPyOAgRjRtgL66l4/0CcGkKtIC8eire3s5KL/rj55ggG38z1MzgS2Gxa2r0JBv8+wdYQUXDkgv2VMYRTyJ514IWnIWrAkZNxwAWZ6s6olC+EVW/72krGpZxaNSItw9TchGtKqjeaLnM5JFeJqIGbtVWsOnY1ykOOsAypIiv0cISRtKU/xyVTBdG15LXNnUz8scoIiHPI8a7MXGmObXZnOgkvAYVt777gC8QtHQ8tvIIA6fLVHvOJx4UpANk6VPrSFYhmt+VP36PYkhfxIse4k6e5lLhWCFiRrfrBgnWD6emBS/yYZ8sbF9bValTGBxB61mpgFlRYddzUilNVt3NjiJhRqUEp9Qe8ax3XB8AuqYaEDsJcx1YzX8fS9ZxHS99izTWt4kOlEcLOFxS3ere9jZEyRZybz8lJ5tfSLd18ysnYlJgsJfmsGDakYGuKiUpWCXWfyIQoNWLz66vJpDL9ZhXSV02FGiC7iYBEwfqWebL00BDN5+dYwgwWq35/MOPTb0e110XICf7JULIBaay5JJTXCwR8pNQ="